### ISSUE TITLE
Add callback for sensor connection

### ISSUE THREAD

**Issue by jonschumacher** [Tinkerforge/ptc-bricklet#1]
Disclaimer: I do not (yet) fully understand the way the bricklet firmware and the API work together.

What I want to do is to use the PTC bricklet for controlling a cooling system. In order to make this system robust I would like to check whether the sensor connection is lost in order to handle things accordingly (e.g. shutdown the system/go into failure mode). I could obviously poll for that information, but this should not be the way to go. Do you think it is reasonable/possible to add a callback for the sensor connection information?

**Comment by borg42** [comment]
I can't see why it wouldn't be technically possible to add this callback. However, the PTC Bricklet is unfortunately obsolete. It will be replaced by the new PTC Bricklet 2.0. See here: https://github.com/Tinkerforge/ptc-v2-bricklet

The PTC Bricklet 2.0 firmware is currently still in development, i will write the callback idea to the TODO list. The new Bricklet will be released in about 1.5 months.

**Comment by jonschumacher** [comment]
Since I already have three PTC bricklets lying around: Can the code be backported to the previous version?

**Comment by borg42** [comment]
It should be possible, we still have 600bytes of space available in the PTC Bricklet plugin. I will take a look when i finish the PTC 2.0. This will probably be in 2-3 weeks.

**Comment by jonschumacher** [comment]
Sounds great!

**Comment by borg42** [comment]
It is implemented, see https://github.com/Tinkerforge/ptc-bricklet/commit/42ef3e4dc2754e4b19a5b8633f8905972912aa66 and https://github.com/Tinkerforge/generators/commit/a704a19bf7083104c98551fbf97979427bdaec4b.

The firmware is already released, the API will be able available with the next release of the bindings.
